# push.yml

#  Name of workflow
name: Push workflow

# When workflow is triggered
on:
  push:
    branches:
      - dev
      - main

# Jobs to carry out
jobs:
  deploy:
    # Operating system to run job on
    runs-on: ubuntu-latest
    # Steps in job
    steps:
      # Get code from repo
      - name: Checkout code
        uses: actions/checkout@v1
      # Install NodeJS
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      # Run npm install and build on our code
      - run: npm install
      - run: npm run build --if-present
      # Run Test
      - name: Run tests
        run: npm run test
      # Deploy to Netlify using our production secrets
      - name: Deploy to netlify
        uses: netlify/actions/cli@master
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.aKMoJ1COg2TtLdvXNSnQPNh4D6CZefhds5bK5LgHTKA }}
          NETLIFY_SITE_ID: ${{ secrets.ed7deb53-b1aa-4c99-8e99-0758d1ac5712 }}
        with:
          args: deploy --dir=build --prod
          secrets: '["aKMoJ1COg2TtLdvXNSnQPNh4D6CZefhds5bK5LgHTKA", "ed7deb53-b1aa-4c99-8e99-0758d1ac5712"]'